services: 
  node: 
    image: node:20.18-alpine3.20
    container_name: lnk-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"